In [2]:
import numpy as np
import pandas as pd

In [5]:
num = [1,2,3,4,5]
num_eng = ['one', 'two', 'three', 'four', 'five']
s = pd.Series(num,
             index=num_eng)

In [7]:
s['three']

3

In [8]:
s

one      1
two      2
three    3
four     4
five     5
dtype: int64

In [9]:
numbers = {'one':1, 'two':2, 'three':3, 'four':4, 'five':5}

In [ ]:
### dict = { key1: value1, key2: value2 }

In [10]:
numbers.keys()

dict_keys(['one', 'two', 'three', 'four', 'five'])

In [11]:
numbers.values()

dict_values([1, 2, 3, 4, 5])

In [12]:
numbers.items()

dict_items([('one', 1), ('two', 2), ('three', 3), ('four', 4), ('five', 5)])

In [13]:
s

one      1
two      2
three    3
four     4
five     5
dtype: int64

In [14]:
s.keys()

Index(['one', 'two', 'three', 'four', 'five'], dtype='object')

In [16]:
s.values

array([1, 2, 3, 4, 5])

In [20]:
for i in s.items():
    print(i)

('one', 1)
('two', 2)
('three', 3)
('four', 4)
('five', 5)


In [21]:
list(s.items())

[('one', 1), ('two', 2), ('three', 3), ('four', 4), ('five', 5)]

In [22]:
numbers

{'one': 1, 'two': 2, 'three': 3, 'four': 4, 'five': 5}

In [23]:
num

[1, 2, 3, 4, 5]

In [24]:
num[3]

4

In [25]:
num[2:4]

[3, 4]

In [26]:
s

one      1
two      2
three    3
four     4
five     5
dtype: int64

In [27]:
s['one']

1

In [28]:
s['three']

3

In [29]:
s[2:4]

three    3
four     4
dtype: int64

In [30]:
s['two':'four']

two      2
three    3
four     4
dtype: int64

In [32]:
s % 2 == 0

one      False
two       True
three    False
four      True
five     False
dtype: bool

In [34]:
s[s%2==0] = 10

In [35]:
s

one       1
two      10
three     3
four     10
five      5
dtype: int64

In [40]:
s.loc['three']

3

In [41]:
s.iloc[3]

10

In [42]:
num

[1, 2, 3, 4, 5]

In [43]:
num_eng

['one', 'two', 'three', 'four', 'five']

In [44]:
num_can = ['yat' , 'yi', 'saam', 'sei', 'm']

In [46]:
num = np.array(num)
num

array([1, 2, 3, 4, 5])

In [48]:
table = num[:,np.newaxis] * num

In [51]:
df = pd.DataFrame(table,
                 index=num_can,
                 columns=num_eng)

In [52]:
df

one  two  three  four  five
yat     1    2      3     4     5
yi      2    4      6     8    10
saam    3    6      9    12    15
sei     4    8     12    16    20
m       5   10     15    20    25

In [53]:
df['three']

yat      3
yi       6
saam     9
sei     12
m       15
Name: three, dtype: int64

In [54]:
df.index

Index(['yat', 'yi', 'saam', 'sei', 'm'], dtype='object')

In [55]:
df.columns

Index(['one', 'two', 'three', 'four', 'five'], dtype='object')

In [56]:
df.values

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [57]:
df.T

yat  yi  saam  sei   m
one      1   2     3    4   5
two      2   4     6    8  10
three    3   6     9   12  15
four     4   8    12   16  20
five     5  10    15   20  25

In [60]:
df

one  two  three  four  five
yat     1    2      3     4     5
yi      2    4      6     8    10
saam    3    6      9    12    15
sei     4    8     12    16    20
m       5   10     15    20    25

In [63]:
df['six'] = df['five'] + df['one']

In [64]:
df

one  two  three  four  five  six
yat     1    2      3     4     5    6
yi      2    4      6     8    10   12
saam    3    6      9    12    15   18
sei     4    8     12    16    20   24
m       5   10     15    20    25   30

In [66]:
df.loc['yat':'sei', 'two':'four']

two  three  four
yat     2      3     4
yi      4      6     8
saam    6      9    12
sei     8     12    16

In [68]:
df.loc['yat','five']

5

In [69]:
df.iloc[0:4, 1:4]

two  three  four
yat     2      3     4
yi      4      6     8
saam    6      9    12
sei     8     12    16

In [87]:
ind = pd.Index([1,2,3])

In [88]:
ind

Int64Index([1, 2, 3], dtype='int64')

In [89]:
df

one  two  three  four  five  six
yat     1    2      3     4     5    6
yi      2    4      6     8    10   12
saam    3    6      9    12    15   18
sei     4    8     12    16    20   24
m       5   10     15    20    25   30

In [91]:
type(df.index)

pandas.core.indexes.base.Index

In [92]:
type(df.columns)

pandas.core.indexes.base.Index

In [93]:
s = pd.Series([3,3,5,6,2])

In [94]:
s

0    3
1    3
2    5
3    6
4    2
dtype: int64

In [95]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [96]:
ind1 = pd.Index([1,2,3])
ind2 = pd.Index([3,4,5])

In [97]:
ind1 | ind2

Int64Index([1, 2, 3, 4, 5], dtype='int64')

In [98]:
ind1 & ind2

Int64Index([3], dtype='int64')

In [99]:
ind1 ^ ind2 ### shift 6

Int64Index([1, 2, 4, 5], dtype='int64')

In [102]:
df

one  two  three  four  five  six
yat     1    2      3     4     5    6
yi      2    4      6     8    10   12
saam    3    6      9    12    15   18
sei     4    8     12    16    20   24
m       5   10     15    20    25   30

In [105]:
df > 3

one    two  three  four  five   six
yat   False  False  False  True  True  True
yi    False   True   True  True  True  True
saam  False   True   True  True  True  True
sei    True   True   True  True  True  True
m      True   True   True  True  True  True

In [106]:
ind1

Int64Index([1, 2, 3], dtype='int64')

In [107]:
ind2

Int64Index([3, 4, 5], dtype='int64')

In [108]:
value1 = [11,22,33]
value2 = [44,55,66]

In [111]:
s1 = pd.Series(value1,index=ind1)
s2 = pd.Series(value2,index=ind2)

In [112]:
s1

1    11
2    22
3    33
dtype: int64

In [113]:
s2

3    44
4    55
5    66
dtype: int64

In [114]:
s1 + s2

1     NaN
2     NaN
3    77.0
4     NaN
5     NaN
dtype: float64

In [116]:
arr = np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [121]:
'abc'

'abc'

In [122]:
list('abc')

['a', 'b', 'c']

In [124]:
df = pd.DataFrame(arr,
                 index=list('abc'),
                 columns=list('PQRS'))
df

P  Q   R   S
a  0  1   2   3
b  4  5   6   7
c  8  9  10  11

In [126]:
df.loc['a']

P    0
Q    1
R    2
S    3
Name: a, dtype: int64

In [127]:
df - df.loc['a']

P  Q  R  S
a  0  0  0  0
b  4  4  4  4
c  8  8  8  8

In [130]:
df.subtract(df.loc['a'])

P  Q  R  S
a  0  0  0  0
b  4  4  4  4
c  8  8  8  8

In [135]:
df.subtract(df['P'], axis=0)

P  Q  R  S
a  0  1  2  3
b  0  1  2  3
c  0  1  2  3

In [136]:
[]

[]

In [138]:
None == 0

False

In [141]:
def f(l):
    l[0] = None


In [143]:
a = [1,2,3]
f(a)

In [144]:
a

[None, 2, 3]

In [145]:
print(f(a))

None


In [146]:
a = [None, 2, 3]

In [147]:
arr = np.array(a)

In [149]:
arr

array([None, 2, 3], dtype=object)

In [150]:
arr.sum()

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

In [151]:
a = [np.nan, 2, 3] ### NaN NAN nan

In [152]:
arr = np.array(a)

In [153]:
arr

array([nan,  2.,  3.])

In [154]:
arr.dtype

dtype('float64')

In [156]:
arr.sum()

nan

In [166]:
a = [np.nan, 2, 3]
s = pd.Series(a)

In [167]:
s.sum()

5.0

In [168]:
s

0    NaN
1    2.0
2    3.0
dtype: float64

In [169]:
s

0    NaN
1    2.0
2    3.0
dtype: float64

In [170]:
s.isnull()

0     True
1    False
2    False
dtype: bool

In [171]:
s.notnull()

0    False
1     True
2     True
dtype: bool

In [175]:
arr = np.random.randn(100,200)
arr[35,65] = np.nan

In [178]:
df = pd.DataFrame(arr)

In [186]:
mask_col = np.any(df.isnull(), axis=0)
mask_row = np.any(df.isnull(), axis=1)

In [187]:
df.loc[mask_row, mask_col]

65
35 NaN

In [189]:
df.shape

(100, 200)

In [193]:
df.dropna(axis=1).shape

(100, 199)

In [195]:
df.fillna(0).shape

(100, 200)

In [207]:
new_df = df.fillna(m)
new_df.iloc[35,65]

-0.006203095811219902

In [204]:
m = new_df.values.mean()

In [205]:
m

-0.006203095811219902